### ISSUE TITLE
Editor warnings

### ISSUE THREAD

**Issue by caxapexac** [Leopotam/globals#1]
Некритично, но некрасиво, весь лог в этой штуке

Refresh: detecting if any assets need to be imported or removed ...
A meta data file (.meta) exists but its asset 'Packages/com.leopotam.globals/bin' can't be found. When moving or deleting files outside of Unity, please ensure that the corresponding .meta file is moved or deleted along with it.
 
(Filename: C:\buildslave\unity\build\Modules/AssetDatabase/Editor/V1/RefreshAssets.cpp Line: 83)

A meta data file (.meta) exists but its asset 'Packages/com.leopotam.globals/obj' can't be found. When moving or deleting files outside of Unity, please ensure that the corresponding .meta file is moved or deleted along with it.
 
(Filename: C:\buildslave\unity\build\Modules/AssetDatabase/Editor/V1/RefreshAssets.cpp Line: 83)

Removing Packages/com.leopotam.globals/bin because the asset does not exist
 
(Filename: C:\buildslave\unity\build\Modules/AssetDatabase/Editor/V1/AssetInterface.cpp Line: 998)

Removing Packages/com.leopotam.globals/obj because the asset does not exist
 
(Filename: C:\buildslave\unity\build\Modules/AssetDatabase/Editor/V1/AssetInterface.cpp Line: 998)

Couldn't delete Packages/com.leopotam.globals/bin because it's in an immutable folder.
 
(Filename: C:\buildslave\unity\build\Modules/AssetDatabase/Editor/V1/AssetInterface.cpp Line: 1263)

Couldn't delete Packages/com.leopotam.globals/obj because it's in an immutable folder.
 
(Filename: C:\buildslave\unity\build\Modules/AssetDatabase/Editor/V1/AssetInterface.cpp Line: 1263)

**Comment by Leopotam** [comment]
@caxapexac bug in npm package only, can you check is it fixed in last version?

**Comment by caxapexac** [comment]
Ok, wait for several minutes

**Comment by caxapexac** [comment]
It's still the same behaviour...

**Comment by Leopotam** [comment]
@caxapexac how you tested? it should be `preview - 2019.12.22` version, not released one.
